2023-12-21 02:46:41,984 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-21 02:46:41,984 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Configure stats pid to 11452
2023-12-21 02:46:41,984 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Lukas Svendsen\.config\wandb\settings
2023-12-21 02:46:41,984 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\settings
2023-12-21 02:46:41,984 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_name': 'fashion-mnist-small', 'notebook_name': 'TryWandb.ipynb'}
2023-12-21 02:46:41,984 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-21 02:46:41,985 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-21 02:46:41,986 INFO    MainThread:11452 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\run-20231221_024641-qhm7f941\logs\debug.log
2023-12-21 02:46:41,986 INFO    MainThread:11452 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\run-20231221_024641-qhm7f941\logs\debug-internal.log
2023-12-21 02:46:41,986 INFO    MainThread:11452 [wandb_init.py:_jupyter_setup():470] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001E0ABB3F9D0>
2023-12-21 02:46:41,986 INFO    MainThread:11452 [wandb_init.py:init():564] calling init triggers
2023-12-21 02:46:41,986 INFO    MainThread:11452 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-21 02:46:41,986 INFO    MainThread:11452 [wandb_init.py:init():614] starting backend
2023-12-21 02:46:41,986 INFO    MainThread:11452 [wandb_init.py:init():618] setting up manager
2023-12-21 02:46:41,992 INFO    MainThread:11452 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-21 02:46:41,994 INFO    MainThread:11452 [wandb_init.py:init():624] backend started and connected
2023-12-21 02:46:42,011 INFO    MainThread:11452 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-21 02:46:42,011 INFO    MainThread:11452 [wandb_init.py:init():716] updated telemetry
2023-12-21 02:46:42,012 INFO    MainThread:11452 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-21 02:46:42,464 ERROR   MainThread:11452 [wandb_init.py:init():775] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-21 02:46:42,628 ERROR   MainThread:11452 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\envs\amlfall23\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "c:\ProgramData\anaconda3\envs\amlfall23\lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-12-21 02:46:49,589 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-21 02:46:49,589 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Configure stats pid to 11452
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Lukas Svendsen\.config\wandb\settings
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\settings
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_name': 'fashion-mnist-small', 'notebook_name': 'TryWandb.ipynb'}
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\run-20231221_024649-e4nmpjrk\logs\debug.log
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\run-20231221_024649-e4nmpjrk\logs\debug-internal.log
2023-12-21 02:46:49,590 INFO    MainThread:11452 [wandb_init.py:init():564] calling init triggers
2023-12-21 02:46:49,591 INFO    MainThread:11452 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-21 02:46:49,591 INFO    MainThread:11452 [wandb_init.py:init():614] starting backend
2023-12-21 02:46:49,591 INFO    MainThread:11452 [wandb_init.py:init():618] setting up manager
2023-12-21 02:46:49,598 INFO    MainThread:11452 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-21 02:46:49,599 INFO    MainThread:11452 [wandb_init.py:init():624] backend started and connected
2023-12-21 02:46:49,619 INFO    MainThread:11452 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-21 02:46:49,620 INFO    MainThread:11452 [wandb_init.py:init():716] updated telemetry
2023-12-21 02:46:49,620 INFO    MainThread:11452 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-21 02:48:20,450 ERROR   MainThread:11452 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-12-21 02:48:20,521 ERROR   MainThread:11452 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\envs\amlfall23\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "c:\ProgramData\anaconda3\envs\amlfall23\lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Current SDK version is 0.16.1
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Configure stats pid to 11452
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from C:\Users\Lukas Svendsen\.config\wandb\settings
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\settings
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'run_name': 'fashion-mnist-small', 'notebook_name': 'TryWandb.ipynb'}
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_init.py:_log_setup():524] Logging user logs to c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\run-20231221_024932-swcusfj4\logs\debug.log
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_init.py:_log_setup():525] Logging internal logs to c:\Users\Lukas Svendsen\Desktop\AML\exam\wandb\run-20231221_024932-swcusfj4\logs\debug-internal.log
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_init.py:init():564] calling init triggers
2023-12-21 02:49:32,142 INFO    MainThread:11452 [wandb_init.py:init():571] wandb.init called with sweep_config: {}
config: {}
2023-12-21 02:49:32,144 INFO    MainThread:11452 [wandb_init.py:init():614] starting backend
2023-12-21 02:49:32,144 INFO    MainThread:11452 [wandb_init.py:init():618] setting up manager
2023-12-21 02:49:32,150 INFO    MainThread:11452 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-12-21 02:49:32,151 INFO    MainThread:11452 [wandb_init.py:init():624] backend started and connected
2023-12-21 02:49:32,169 INFO    MainThread:11452 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2023-12-21 02:49:32,169 INFO    MainThread:11452 [wandb_init.py:init():716] updated telemetry
2023-12-21 02:49:32,169 INFO    MainThread:11452 [wandb_init.py:init():749] communicating run to backend with 90.0 second timeout
2023-12-21 02:51:02,984 ERROR   MainThread:11452 [wandb_init.py:init():775] encountered error: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
2023-12-21 02:51:03,056 ERROR   MainThread:11452 [wandb_init.py:init():1188] Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
Traceback (most recent call last):
  File "c:\ProgramData\anaconda3\envs\amlfall23\lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
  File "c:\ProgramData\anaconda3\envs\amlfall23\lib\site-packages\wandb\sdk\wandb_init.py", line 781, in init
    raise error
wandb.errors.CommError: Run initialization has timed out after 90.0 sec. 
Please refer to the documentation for additional information: https://docs.wandb.ai/guides/track/tracking-faq#initstarterror-error-communicating-with-wandb-process-
